---
version: '3'
services:
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    expose:
      - "3000"
    ports:
      - "3000:3000"

  mongodb:
    image: "mongo:5.0.8-focal"
    volumes:
      - ./db:/db
    ports:
      - "27017:27017"
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
  
  exercisecabify:
    depends_on:
      - mongodb
      - messageapp
    build: .
    expose:
      - "9001"
    ports:
      - "9001:9001"
    links:
      - "messageapp:messageDB"


