version: "3"
services:
  registrator:
    image: gliderlabs/registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: -internal consul://consul:8500
    depends_on:
      - consul
    links:
      - consul
  
  consul: 
    image: consul
    command: "agent -server -bootstrap -ui -client=0.0.0.0 -bind='{{ GetPrivateIP }}'"

  balancer:
    image: haproxy:1.8-alpine
    depends_on:
      - registrator
    links:
      - registrator
    volumes: 
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 48151:48151

  service:
    image: tutum/hello-world
    deploy:
      replicas: 5
    links:
      - balancer
    ports:
      - 80
    environment:
      - SERVICE_NAME=service-v1

  service-2:
    image: tutum/hello-world
    deploy:
      replicas: 1
    links:
      - balancer
    ports:
      - 80
    environment:
      - SERVICE_NAME=service-v2
