version: "3"
services:
  cabifyapp:
    build: .
    ports:
      - "9003:9003"
    depends_on:
      - mongodb
      - cache
      - redis-commander
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
  mongobackup:
    depends_on:
      - mongodb
    image: mongo
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod2.log'
    volumes:
      - ./data/db2:/data/db2
    ports:
      - 27018:27017
    restart: always
  cache:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - cache:/data
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - 8081:8081
volumes:
  cache:
    driver: local

